version: '3.7'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: netsoc-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ulimits: # some OSs need this
      nofile:
        soft: 122880
        hard: 122880
    ports:
      - 9200:9200
      - 9300:9300   

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    depends_on: 
      - elasticsearch
      - kibana
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: netsoc-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  