version: '3.7'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: fyp-elasticsearch
    user: 1000:1000
    volumes: 
      - ./data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ulimits: # some OSs need this
      nofile:
        soft: 122880
        hard: 122880
    ports:
      - 9200:9200
      - 9300:9300   

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fyp-jaeger
    restart: on-failure
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    depends_on: 
      - elasticsearch
      - kibana
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: fyp-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  
  hotrot:
    image: jaegertracing/example-hotrod
    container_name: fyp-hotrod
    command: all
    restart: on-failure
    environment: 
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
    ports:
      - 8080-8083:8080-8083
    depends_on: 
      - jaeger
    