/*
* This Kotlin source file was generated by the Gradle 'init' task.
*/
package xyz.noahsc.topology

import io.ktor.application.Application
import io.ktor.application.ApplicationStopped
import io.ktor.application.ApplicationStarting
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.features.CallLogging
import io.ktor.features.ContentNegotiation
import io.ktor.gson.gson
import io.ktor.http.ContentType
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.cio.CIO
import io.ktor.server.engine.embeddedServer
import io.ktor.util.KtorExperimentalAPI
import mbuhot.eskotlin.query.compound.bool
import mbuhot.eskotlin.query.term.term
import mbuhot.eskotlin.query.term.range
import org.elasticsearch.index.query.TermQueryBuilder
import org.elasticsearch.client.RestClient
import org.elasticsearch.client.RestHighLevelClient
import org.elasticsearch.action.search.SearchRequest
import org.elasticsearch.search.builder.SearchSourceBuilder
import org.elasticsearch.client.RequestOptions
import org.apache.http.HttpHost
import org.slf4j.LoggerFactory
import com.apurebase.kgraphql.KGraphQL

data class Driver(val id: Int, val firstName: String, val lastName: String, val nationality: String)

@UseExperimental(KtorExperimentalAPI::class)
fun main(args: Array<String>) {
    val server = embeddedServer(CIO, 8080, module = Application::module)
    server.start(wait = true)
}

data class Fruit(val name: String, val weight: Float)

fun Application.module() {
    val lowLevel = RestClient.builder(HttpHost("localhost", 9200))
    val client: RestHighLevelClient = RestHighLevelClient(lowLevel)
    
    install(ContentNegotiation) {
        gson {
            setPrettyPrinting()
        }
    }
    
    install(CallLogging) { }
    
    environment.monitor.subscribe(ApplicationStopped) { 
        client.close()
    }
    
    routing {
        get("/drivers") {
            val query = bool { 
                must {
                    term { "operationName" to "actor.ActorFunc/*main.request"}
                }
            }
            
            val request = SearchRequest("jaeger-span-*")
            val builder = SearchSourceBuilder()
            builder.query(query)
            request.source(builder)
            val resp = client.search(request, RequestOptions.DEFAULT)
            call.respond(resp.hits.hits.map { it.sourceAsMap })
        }
        
        get("/schema") {
            val schema = KGraphQL.schema { 
                configure { 
                    useDefaultPrettyPrinter = true
                 }
                query("trace") { 
                    resolver { name: String, weight: Float ->
                        Fruit(name, weight)
                    }
                }
                type<Fruit>()
            }
            
            call.respond(schema.execute("""{
                trace(name: "epic", weight: 5.0) {
                    name
                    weight
                }
            }""".trimIndent()))
        }
    }
}